### ISSUE TITLE
Request to update library in nuget as well as github

### ISSUE THREAD

**Issue by prakash-malodiya** [NAXAM/braintreedropin-android-binding#2]
We are using your nuget package 3.2.1 in one of our project. We need latest update from braintree as not other library found for that. So please update your library in nuget as well as github.

**Comment by ericc0504** [comment]
Is it keep supporting?

**Comment by tuyen-vuduc** [comment]
It really takes time to update a big library like this one. Normally, it comes with a cost. 
Atm, we don't have a project using Braintree, so no updates will be available soon.
I hope community could upgrade based on the real need then create a PR here.
Looking forward to reviewing and approving a PR.

Cheers.

**Comment by tuyen-vuduc** [comment]
Latest package is being published.
